[package]
name = "pretty_html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsley = { workspace = true }
txml = { path = "../txml" }
